"""pairwise comparisons — Pairwise Comparison Framework (E-21)

Adds the pairwise_comparisons table: head-to-head "A vs B" comparisons between two
task results on a subject axis (model / template / prompt), decided by an LLM judge
(with position-bias mitigation) or a human. Candidate B is either an existing task
or generated by re-running a source task with overrides. Judged comparisons feed
real matches to the E-19 ranking engine (the ELO leaderboard). Both judge and human
verdicts live on the row so judge↔human agreement (E-17) is row-local.

Revision ID: f4a5b6c7d8e9
Revises: e3f4a5b6c7d8
Create Date: 2026-06-10
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


revision = "f4a5b6c7d8e9"
down_revision = "e3f4a5b6c7d8"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "pairwise_comparisons",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(20), nullable=False, server_default="model"),
        sa.Column(
            "source_task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "task_a_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "task_b_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("b_run_config", JSONB(), nullable=True),
        sa.Column("player_a", sa.String(255), nullable=True),
        sa.Column("player_b", sa.String(255), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("judge_mode", sa.String(10), nullable=False, server_default="llm"),
        sa.Column("judge_verdict", sa.String(4), nullable=True),
        sa.Column("human_verdict", sa.String(4), nullable=True),
        sa.Column("judge_detail", JSONB(), nullable=True),
        sa.Column("human_by", sa.String(255), nullable=True),
        sa.Column("human_reasoning", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(10, 6), server_default="0"),
        sa.Column("created_by", sa.String(255), server_default="user"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "idx_pairwise_comparisons_workspace", "pairwise_comparisons", ["workspace_id"]
    )
    op.create_index(
        "idx_pairwise_comparisons_status", "pairwise_comparisons", ["status"]
    )


def downgrade():
    op.drop_table("pairwise_comparisons")
