import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Swords, Scale, Trophy, Plus, RefreshCw } from 'lucide-react'
import { qualityApi } from '@/api/client'
import { useAuth } from '@/stores/auth'
import type {
  ComparisonSubject,
  PairwiseComparison,
  PairwiseVerdict,
} from '@/types'
import { cn } from '@/lib/utils'

/** Pairwise Comparison Framework (E-21): "which is better, A or B?" between two
 *  task results on a subject axis (model / template / prompt). An LLM judge
 *  (position-bias mitigated — the same pair judged in both orders, agree → winner,
 *  disagree → tie) or a human picks the winner; judged verdicts feed the E-19 ELO
 *  leaderboard. Candidate B is an existing task (direct) or generated by re-running
 *  a source with an override. */
export default function PairwisePanel() {
  const role = useAuth((s) => s.workspaces.find((w) => w.id === s.workspaceId)?.role ?? null)
  const isAdmin = role === 'owner' || role === 'admin'
  const queryClient = useQueryClient()
  const [selected, setSelected] = useState<string | null>(null)
  const [leaderboardMsg, setLeaderboardMsg] = useState<string | null>(null)

  const list = useQuery({
    queryKey: ['pairwise', 'list'],
    queryFn: () => qualityApi.listComparisons(),
  })

  const leaderboard = useMutation({
    mutationFn: () => qualityApi.runPairwiseLeaderboard({ subject: 'model', method: 'elo' }),
    onSuccess: (r) =>
      setLeaderboardMsg(
        `Ranked ${r.n_players} players from ${r.n_matches} matches → ${r.ranking_key} v${r.version}. See the Leaderboard tab.`,
      ),
  })

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['pairwise', 'list'] })
    if (selected) queryClient.invalidateQueries({ queryKey: ['pairwise', 'detail', selected] })
  }

  const comparisons = list.data?.comparisons ?? []
  const agreement = list.data?.agreement

  return (
    <div className="bg-white rounded-lg border p-4 space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <h2 className="text-lg font-semibold flex items-center gap-2">
          <Swords className="h-5 w-5" />
          Pairwise <span className="text-sm font-normal text-gray-400">(E-21)</span>
        </h2>
        {isAdmin && (
          <button
            onClick={() => {
              setLeaderboardMsg(null)
              leaderboard.mutate()
            }}
            disabled={leaderboard.isPending}
            className="flex items-center gap-1.5 px-3 py-1.5 border rounded-lg text-sm hover:bg-gray-50 disabled:opacity-50"
          >
            <Trophy className="h-4 w-4" />
            Push to ELO leaderboard
          </button>
        )}
      </div>

      <p className="text-xs text-gray-500">
        Compare two answers head-to-head — more reliable than pointwise scores, which cluster into
        7-8. The LLM judge judges the same pair in both orders and reconciles (agree → winner,
        disagree → tie + position-bias flag); or a human picks the winner. Judged verdicts feed the
        ELO leaderboard via the Aggregation Engine (E-19).
      </p>

      {leaderboardMsg && <p className="text-xs text-green-700">{leaderboardMsg}</p>}
      {leaderboard.isError && (
        <p className="text-xs text-red-600">Leaderboard failed — needs judged comparisons and owner/admin.</p>
      )}

      {agreement && agreement.n > 0 && (
        <div className="text-xs text-gray-600">
          Judge↔human agreement:{' '}
          <span className="font-medium text-gray-800">
            {agreement.agreement == null ? '—' : `${Math.round(agreement.agreement * 100)}%`}
          </span>{' '}
          <span className="text-gray-400">
            ({agreement.agreements}/{agreement.n})
          </span>
        </div>
      )}

      {isAdmin && <CreateForm onCreated={(id) => { invalidate(); setSelected(id) }} />}

      <div className="grid grid-cols-1 lg:grid-cols-[20rem_1fr] gap-4">
        <ComparisonList
          comparisons={comparisons}
          loading={list.isLoading}
          selected={selected}
          onSelect={setSelected}
        />
        <ComparisonDetail id={selected} isAdmin={isAdmin} onChanged={invalidate} />
      </div>
    </div>
  )
}

function CreateForm({ onCreated }: { onCreated: (id: string) => void }) {
  const [mode, setMode] = useState<'direct' | 'generated'>('direct')
  const [subject, setSubject] = useState<ComparisonSubject>('model')
  const [taskA, setTaskA] = useState('')
  const [taskB, setTaskB] = useState('')
  const [source, setSource] = useState('')
  const [modelId, setModelId] = useState('')
  const [soulMd, setSoulMd] = useState('')
  const [judgeMode, setJudgeMode] = useState<'llm' | 'human'>('llm')

  const create = useMutation({
    mutationFn: () => {
      if (mode === 'direct') {
        return qualityApi.createComparison({
          subject,
          task_a_id: taskA.trim(),
          task_b_id: taskB.trim(),
          judge_mode: judgeMode,
        })
      }
      const b_run_config: Record<string, unknown> = {}
      if (modelId.trim()) b_run_config.model_id = modelId.trim()
      if (soulMd.trim()) b_run_config.soul_md = soulMd.trim()
      return qualityApi.createComparison({
        subject,
        task_a_id: (taskA.trim() || source.trim()),
        source_task_id: source.trim(),
        b_run_config,
        judge_mode: judgeMode,
      })
    },
    onSuccess: (c) => onCreated(c.id),
  })

  const canSubmit =
    mode === 'direct'
      ? taskA.trim() && taskB.trim()
      : source.trim() && (modelId.trim() || soulMd.trim())

  return (
    <div className="border rounded-lg p-3 space-y-2.5 bg-gray-50/50">
      <div className="flex items-center gap-2 flex-wrap text-xs">
        <Segmented
          value={mode}
          onChange={(v) => setMode(v as 'direct' | 'generated')}
          options={[
            { value: 'direct', label: 'Two tasks' },
            { value: 'generated', label: 'Generate B' },
          ]}
        />
        <Segmented
          value={subject}
          onChange={(v) => setSubject(v as ComparisonSubject)}
          options={[
            { value: 'model', label: 'Model' },
            { value: 'template', label: 'Template' },
            { value: 'prompt', label: 'Prompt' },
          ]}
        />
        <Segmented
          value={judgeMode}
          onChange={(v) => setJudgeMode(v as 'llm' | 'human')}
          options={[
            { value: 'llm', label: 'LLM judge' },
            { value: 'human', label: 'Human' },
          ]}
        />
      </div>

      {mode === 'direct' ? (
        <div className="flex items-center gap-2 flex-wrap">
          <input
            value={taskA}
            onChange={(e) => setTaskA(e.target.value)}
            placeholder="task A id"
            className="flex-1 min-w-[12rem] border rounded-lg px-3 py-1.5 text-sm font-mono"
          />
          <input
            value={taskB}
            onChange={(e) => setTaskB(e.target.value)}
            placeholder="task B id"
            className="flex-1 min-w-[12rem] border rounded-lg px-3 py-1.5 text-sm font-mono"
          />
        </div>
      ) : (
        <div className="space-y-2">
          <div className="flex items-center gap-2 flex-wrap">
            <input
              value={source}
              onChange={(e) => setSource(e.target.value)}
              placeholder="source task id (= candidate A)"
              className="flex-1 min-w-[14rem] border rounded-lg px-3 py-1.5 text-sm font-mono"
            />
            <input
              value={modelId}
              onChange={(e) => setModelId(e.target.value)}
              placeholder="override model id (optional)"
              className="flex-1 min-w-[12rem] border rounded-lg px-3 py-1.5 text-sm font-mono"
            />
          </div>
          <textarea
            value={soulMd}
            onChange={(e) => setSoulMd(e.target.value)}
            placeholder="override soul_md / prompt for B (optional)"
            rows={2}
            className="w-full border rounded-lg px-3 py-1.5 text-sm"
          />
          <p className="text-[11px] text-gray-400">
            Candidate B is a re-run of the source with the override; it runs async and is judged
            automatically when ready.
          </p>
        </div>
      )}

      <div className="flex items-center gap-2">
        <button
          onClick={() => create.mutate()}
          disabled={!canSubmit || create.isPending}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-900 text-white rounded-lg text-sm hover:bg-gray-800 disabled:opacity-50"
        >
          <Plus className="h-4 w-4" />
          Create comparison
        </button>
        {create.isError && <span className="text-xs text-red-600">Create failed — check the ids.</span>}
      </div>
    </div>
  )
}

function ComparisonList({
  comparisons,
  loading,
  selected,
  onSelect,
}: {
  comparisons: PairwiseComparison[]
  loading: boolean
  selected: string | null
  onSelect: (id: string) => void
}) {
  if (loading) return <p className="text-sm text-gray-400">Loading…</p>
  if (comparisons.length === 0)
    return <p className="text-sm text-gray-400">No comparisons yet.</p>
  return (
    <div className="space-y-1.5 max-h-[28rem] overflow-y-auto pr-1">
      {comparisons.map((c) => (
        <button
          key={c.id}
          onClick={() => onSelect(c.id)}
          className={cn(
            'w-full text-left border rounded-lg p-2.5 hover:bg-gray-50 transition-colors',
            selected === c.id && 'border-gray-900 bg-gray-50',
          )}
        >
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-gray-700 truncate">
              {c.player_a ?? '?'} <span className="text-gray-400">vs</span> {c.player_b ?? '?'}
            </span>
            <StatusChip status={c.status} />
          </div>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-[10px] uppercase tracking-wide text-gray-400">{c.subject}</span>
            {c.judge_verdict && <VerdictChip label="judge" verdict={c.judge_verdict} />}
            {c.human_verdict && <VerdictChip label="human" verdict={c.human_verdict} />}
            {c.judge_detail?.position_bias_detected && (
              <span className="text-[10px] text-amber-600">position-bias</span>
            )}
          </div>
        </button>
      ))}
    </div>
  )
}

function ComparisonDetail({
  id,
  isAdmin,
  onChanged,
}: {
  id: string | null
  isAdmin: boolean
  onChanged: () => void
}) {
  const [reasoning, setReasoning] = useState('')
  const detail = useQuery({
    queryKey: ['pairwise', 'detail', id],
    queryFn: () => qualityApi.getComparison(id!),
    enabled: !!id,
  })

  const judge = useMutation({
    mutationFn: () => qualityApi.judgeComparison(id!),
    onSuccess: onChanged,
  })
  const humanVerdict = useMutation({
    mutationFn: (verdict: PairwiseVerdict) =>
      qualityApi.setComparisonHumanVerdict(id!, { verdict, reasoning: reasoning.trim() || undefined }),
    onSuccess: onChanged,
  })

  if (!id) return <p className="text-sm text-gray-400">Select a comparison to inspect.</p>
  if (detail.isLoading) return <p className="text-sm text-gray-400">Loading…</p>
  const c = detail.data
  if (!c) return <p className="text-sm text-amber-700">Comparison not found.</p>

  const sides = c.side_by_side
  const ready = c.status === 'ready' || c.status === 'judged'

  return (
    <div className="space-y-3 border rounded-lg p-3">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <StatusChip status={c.status} />
          <span className="text-[10px] uppercase tracking-wide text-gray-400">{c.subject}</span>
          {c.judge_detail?.position_bias_detected && (
            <span className="text-[11px] text-amber-600">position bias detected</span>
          )}
        </div>
        {isAdmin && ready && (
          <button
            onClick={() => judge.mutate()}
            disabled={judge.isPending}
            className="flex items-center gap-1.5 px-2.5 py-1 border rounded-lg text-xs hover:bg-gray-50 disabled:opacity-50"
          >
            <Scale className={cn('h-3.5 w-3.5', judge.isPending && 'animate-pulse')} />
            {c.judge_verdict ? 'Re-judge (LLM)' : 'Judge (LLM)'}
          </button>
        )}
      </div>

      {c.status === 'generating' && (
        <p className="text-sm text-gray-500 flex items-center gap-1.5">
          <RefreshCw className="h-4 w-4 animate-spin" /> Generating candidate B…
        </p>
      )}
      {c.status === 'failed' && (
        <p className="text-sm text-red-600">
          Failed{c.judge_detail?.error ? `: ${c.judge_detail.error}` : ''}.
        </p>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <SideCard label="A" side={sides?.a} winner={verdictWinner(c.judge_verdict, c.human_verdict, 'a')} />
        <SideCard label="B" side={sides?.b} winner={verdictWinner(c.judge_verdict, c.human_verdict, 'b')} />
      </div>

      {(c.judge_verdict || c.human_verdict) && (
        <div className="flex items-center gap-3 text-xs">
          {c.judge_verdict && <VerdictChip label="judge" verdict={c.judge_verdict} />}
          {c.human_verdict && <VerdictChip label="human" verdict={c.human_verdict} />}
          {c.judge_detail?.judge_model && (
            <span className="text-gray-400">judge: {c.judge_detail.judge_model}</span>
          )}
        </div>
      )}

      {c.judge_detail?.orders && (
        <div className="text-[11px] text-gray-500 space-y-0.5">
          {c.judge_detail.orders.ab && (
            <div>order A,B → <b>{c.judge_detail.orders.ab.winner}</b>: {c.judge_detail.orders.ab.reasoning}</div>
          )}
          {c.judge_detail.orders.ba && (
            <div>order B,A → <b>{c.judge_detail.orders.ba.winner_mapped}</b> (mapped): {c.judge_detail.orders.ba.reasoning}</div>
          )}
        </div>
      )}

      {isAdmin && ready && (
        <div className="border-t pt-2.5 space-y-2">
          <p className="text-xs text-gray-500">Human verdict</p>
          <input
            value={reasoning}
            onChange={(e) => setReasoning(e.target.value)}
            placeholder="reasoning (optional)"
            className="w-full border rounded-lg px-3 py-1.5 text-sm"
          />
          <div className="flex items-center gap-2">
            {(['a', 'b', 'tie'] as PairwiseVerdict[]).map((v) => (
              <button
                key={v}
                onClick={() => humanVerdict.mutate(v)}
                disabled={humanVerdict.isPending}
                className={cn(
                  'px-3 py-1.5 border rounded-lg text-sm hover:bg-gray-50 disabled:opacity-50',
                  c.human_verdict === v && 'border-gray-900 bg-gray-100 font-medium',
                )}
              >
                {v === 'tie' ? 'Tie' : v === 'a' ? 'A wins' : 'B wins'}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function verdictWinner(
  judge: PairwiseVerdict | null,
  human: PairwiseVerdict | null,
  side: 'a' | 'b',
): boolean {
  return judge === side || human === side
}

function SideCard({
  label,
  side,
  winner,
}: {
  label: string
  side?: { player: string | null; title?: string; model_used?: string | null; result_summary?: string; weighted_score?: number | null; missing?: boolean } | null
  winner: boolean
}) {
  if (!side) return <div className="border rounded-lg p-2.5 text-xs text-gray-400">Answer {label}: pending</div>
  if (side.missing)
    return <div className="border rounded-lg p-2.5 text-xs text-amber-600">Answer {label}: task missing</div>
  return (
    <div className={cn('border rounded-lg p-2.5 space-y-1', winner && 'border-green-400 bg-green-50/40')}>
      <div className="flex items-center justify-between gap-2">
        <span className="text-xs font-semibold text-gray-700">Answer {label}</span>
        {winner && <span className="text-[10px] text-green-700">winner</span>}
      </div>
      <div className="text-[11px] text-gray-500 truncate">{side.player ?? side.model_used ?? '—'}</div>
      {side.weighted_score != null && (
        <div className="text-[11px] text-gray-400">pointwise: {side.weighted_score}</div>
      )}
      <p className="text-xs text-gray-700 whitespace-pre-wrap max-h-40 overflow-y-auto">
        {side.result_summary || '(empty)'}
      </p>
    </div>
  )
}

function StatusChip({ status }: { status: string }) {
  const tone =
    status === 'judged'
      ? 'bg-green-50 text-green-700 border-green-200'
      : status === 'failed'
        ? 'bg-red-50 text-red-700 border-red-200'
        : status === 'generating'
          ? 'bg-blue-50 text-blue-700 border-blue-200'
          : 'bg-gray-50 text-gray-600 border-gray-200'
  return <span className={cn('px-1.5 py-0.5 rounded text-[10px] border', tone)}>{status}</span>
}

function VerdictChip({ label, verdict }: { label: string; verdict: PairwiseVerdict }) {
  const text = verdict === 'tie' ? 'tie' : verdict.toUpperCase()
  return (
    <span className="px-1.5 py-0.5 rounded text-[10px] bg-gray-100 text-gray-700 border border-gray-200">
      {label}: {text}
    </span>
  )
}

function Segmented({
  value,
  onChange,
  options,
}: {
  value: string
  onChange: (v: string) => void
  options: { value: string; label: string }[]
}) {
  return (
    <div className="inline-flex rounded-lg border overflow-hidden text-xs">
      {options.map((o) => (
        <button
          key={o.value}
          onClick={() => onChange(o.value)}
          className={cn(
            'px-2.5 py-1.5 hover:bg-gray-50',
            value === o.value ? 'bg-gray-100 font-medium text-gray-800' : 'text-gray-500',
          )}
        >
          {o.label}
        </button>
      ))}
    </div>
  )
}
